kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
    DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api  
        project: expense
    spec:
      initContainers:
      - name: mysql-check
        image: busybox:1.28
        command: ['sh','-c',"until nslookup mysql;do echo waiting for mysql;sleep 2; done"]

      containers:
      - name: backend
        image: rajikakani412/backend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits: # limits should be greater than or equal to requests
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: backend
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service 
metadata:
  namespace: expense
  name: backend
  
spec:
  selector:
   app: backend
   tier: api
   project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 # this is service port
    targetPort: 8080 # this is container port.
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: expense
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: backend
  targetCPUUtilizationPercentage:  15 # usually 75 or more in real env